### ISSUE TITLE
No support for JSX syntax highlight 

### ISSUE THREAD

**Issue by anIddan** [zaggino/brackets-eslint#23]
I've been using this extension for some time and I love it! Lately a great port for CodeMirror's syntax for JSX was ported correctly to Brackets (https://github.com/apla/brackets-jsx) and I was wondering: can you can make it work with the plugin?

**Comment by zaggino** [comment]
@anIddan That should be resolved by https://github.com/zaggino/brackets-eslint/pull/22
cc @petetnt

**Comment by r-flash** [comment]
It actualy works with JSX UNLESS the apla/brackets-jsx extension is installed.

I really don't understand the Brackets' language system well, but i'd guess that the problem comes from the mechanism brackets-jsx uses to target .jsx files [here](https://github.com/apla/brackets-jsx/blob/83bf673bb96f38a9e022381c65f1b2f68bb6dd2f/main.js#L1243).

**Comment by zaggino** [comment]
Have you tried installing the latest version @r-flash ?
@anIddan @petetnt Can you also test this please ?

**Comment by r-flash** [comment]
@zaggino yes, i tested it with last versions of both extensions.

**Comment by zaggino** [comment]
Let me know how you'll go with `2.1.2`

**Comment by r-flash** [comment]
Works for me! Thanks, this war really quick.

**Comment by petetnt** [comment]
Yup, there's that caveat as mentioned in my PR: https://github.com/zaggino/brackets-eslint/pull/22#issue-124915963 (`brackets-jsx` messes up with the language id's).

https://github.com/zaggino/brackets-eslint/commit/6ee83a0dd8c943f9fc80a65ee3f61d7386d79148 is a good temp fix, should be reverted when https://github.com/adobe/brackets/pull/12177 lands
