### ISSUE TITLE
ESLint terminated with error: Max connection attempts reached	

### ISSUE THREAD

**Issue by JackPu** [zaggino/brackets-eslint#53]
![image](https://cloud.githubusercontent.com/assets/4744967/22240012/ffa7213c-e253-11e6-8850-25b745ac46c1.png)

When I installed brackets-eslint, every JS file report this error?Any one else meet the same problem?

**Comment by zaggino** [comment]
@JackPu the issue is with connection to NodeJS is broken. Check the error console (Debug -> Show Developer Tools) for hints, why that might be.

You can see long discussions about it here https://github.com/zaggino/brackets-git/issues/410 or here https://github.com/zaggino/brackets-git/issues/468 or here https://github.com/zaggino/brackets-git/search?q=Max+connection+attempts+&type=Issues&utf8=%E2%9C%93

But ultimately, it's a Brackets shell issue. Doesn't happen in Brackets-Electron.

**Comment by JackPu** [comment]
@zaggino  Thanks a lot.I have solved it.

**Comment by AnuragCh2016** [comment]
@JackPu hey man if you don't mind, how _did_ you solve the issue?
