### ISSUE TITLE
Typos in README Configuration defaults

### ISSUE THREAD

**Issue by lkcampbell** [zaggino/brackets-eslint#67]
I didn't notice this until after I updated the README in my last contribution.

The preference names in the README are incorrect.

Any instance of `"brackets-eslint.gutterMarks"` and `"brackets-eslint.useLocalESLint"` needs to be changed to `"zaggino.brackets-eslint.gutterMarks"` and `"zaggino.brackets-eslint.useLocalESLint"`, respectively.

**Comment by zaggino** [comment]
@lkcampbell readme is correct

the extension has `zaggino.brackets-eslint` id when uploaded to brackets registry because some other extension is blocking `brackets-eslint` id

the extension has `brackets-eslint` id when published to npm

**Comment by lkcampbell** [comment]
@zaggino forgive my ignorance, but have we moved to using npm for extension updates?

**Comment by zaggino** [comment]
@lkcampbell nope, but for a long time, brackets-eslint couldn't be in brackets registry because it did not support node_modules

i've created https://github.com/zaggino/brackets-npm-registry to go around that, you can use it to install extensions published to npm

i've also done https://github.com/adobe/brackets/pull/10602 which was merged much later after brackets-npm-registry was created

currently, you can use both ways to install brackets-eslint

**Comment by lkcampbell** [comment]
@zaggino just wondering, because I am have been recently getting a certificate security warning from the Brackets registry site.
